# Logistic Regression
#### Logistic Regression is a supervised learning classification algorithm used to predict probabilities of a binary outcome.

#### Despite the name “regression,” it is mainly used for: Binary Classification

## Examples:
<ul>
    <li>Spam / Not Spam</li>
    <li>Pass / Fail</li>
    <li>Disease / No Disease</li>
</ul>

---

## Why Not Use Linear Regression for Classification?
#### Linear regression:
#### Outputs values from 
#### ```−∞ to +∞```
#### Not suitable for probabilities

#### We need output between:
#### ```0 ≤ p ≤ 1```
#### So we use the Sigmoid Function.

---

## The Sigmoid Function (Logistic Function)
#### ```σ(z) = 1 / (1 + exp(-z))```
#### Where:
#### ```z = β0 ​+ β1.​x1 ​+ ... + βn.​xn​```
### Properties:
<ul>
    <li>Output range: (0,1)</li>
    <li>S-shaped curve</li>
    <li>Converts linear output into probability</li>
</ul>

## Model Representation
#### Step 1: Compute linear combination
#### ```z = β0 ​+ β1.​x1 ​+ ... + βn.​xn​```
#### Step 2: Apply sigmoid
#### ``` y^​ = σ(z) ```
#### Output:
<ul>
    <li>If probability ≥ 0.5 → Class 1</li>
    <li>If probability < 0.5 → Class 0</li>
</ul>

---

## Interpretation in Terms of Odds
#### Logistic regression models:
### Log-Odds
#### ``` log(p / (1−p)​) = β0 ​+ β1.​x1 ​+ ... + βn.​xn```
#### Where:
<ul>
    <li>p = probability of class 1</li>
    <li>p/(1−p) = odds​</li>
</ul>

---

## Cost Function (Loss Function)
#### We cannot use MSE (Mean Squared Error).
#### Instead we use:
#### Binary Cross-Entropy Loss (Log Loss)
#### ```J(β) = − (1 / m)​.∑[ylog(y^​) + (1 − y).log(1 − y^​)]```
#### Why?
<ul>
    <li>Makes optimization convex</li>
    <li>Works well with probabilities</li>
</ul>

---

## Decision Boundary
#### Decision boundary occurs when:
#### ```p = 0.5```
#### Which means:
#### ```β0 ​+ β1.​x1 ​+ ... + βn.​xn​ = 0```
#### It is:
<ul>
    <li>Linear for basic logistic regression</li>
    <li>Can be nonlinear using polynomial features</li>
</ul>

---

# Multiclass Logistic Regression
#### For more than 2 classes:
#### Use:
#### ```Softmax Regression```
#### (Also called Multinomial Logistic Regression)


In [7]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [9]:
df = pd.read_csv('heart.csv')

In [10]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [12]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:-1], df.iloc[:, -1], test_size=0.2, random_state=12)

In [15]:
# ogistic Regression uses an optimizer (by default = 100):
#lbfgs
#This solver tries to minimize the log loss.

clf1 = LogisticRegression(max_iter=1000) 
clf2 = DecisionTreeClassifier()

In [16]:
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)

DecisionTreeClassifier()

In [17]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [20]:
print("Accuracy Score of Logistic Regression: ", accuracy_score(y_test, y_pred1))
print("Accuracy Score of Decision Tree: ", accuracy_score(y_test, y_pred2))

Accuracy Score of Logistic Regression:  0.7704918032786885
Accuracy Score of Decision Tree:  0.7540983606557377


In [21]:
 confusion_matrix(y_test, y_pred1)

array([[23,  8],
       [ 6, 24]])

In [22]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



0   1
0  23   8
1   6  24

In [23]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix



0   1
0  23   8
1   7  23

In [24]:
result = pd.DataFrame()
result['Actual_Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [25]:
result.sample(10)

Actual_Label  Logistic Regression Prediction  Decision Tree Prediction
37              1                               0                         0
263             0                               0                         1
251             0                               0                         0
6               1                               1                         1
78              1                               1                         1
216             0                               0                         0
279             0                               0                         0
262             0                               0                         0
264             0                               0                         0
75              1                               1                         1

In [26]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [27]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  23   8
1   6  24
--------------------------------------------------
Precision -  0.75
Recall -  0.8
F1 score -  0.7741935483870969


In [28]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
    0   1
0  23   8
1   7  23
--------------------------------------------------
Precision -  0.7419354838709677
Recall -  0.7666666666666667
F1 score -  0.7540983606557377


In [29]:
precision_score(y_test,y_pred1,average=None)

array([0.79310345, 0.75      ])

In [30]:
precision_score(y_test,y_pred2,average=None)

array([0.76666667, 0.74193548])